### ISSUE TITLE
date vs dt

### ISSUE THREAD

**Issue by kenstowe** [Djones4822/pyTeamUp#4]
Looks like there is a mix use of "date" and "dt" as parameters and variables. Even when having the same purpose, start_date and start_dt. 

Example get_event_collection() vs new_event()

Is there a reason for this? Can there be an update that standardize on one or the other?

**Comment by Djones4822** [comment]
Yes I will review tonight and try to push an update soon, thanks for pointing that out!

**Comment by Djones4822** [comment]
I have pushed a new version that eliminates `date` usages in favor of `dt` to this repo, pypi is not updated yet. I tested the code provided in the readme and all worked. Let me know if you encounter any issues or have any other suggestions. Pull requests are welcome if you have improvements or optimizations you'd like to see.

I also made some other small tweaks, documented in the readme. Hopefully nothing breaking...

I will update the Pypi project this weekend.

**Comment by Djones4822** [comment]
Thanks for your pull request, I have merged your change then removed the python2 versioning. Also corrected the dateutil package name inside the setup.py for pypi uploading. Package on pypi is now consistent with github, installing or upgrading with pip should be fine.

Closing for now, let me know if any problems. Thanks again!
