### ISSUE TITLE
Requests exception handling

### ISSUE THREAD

**Issue by kenstowe** [Djones4822/pyTeamUp#6]
None of the various Requests exceptions are handled by pyteamup. For example requests.exceptions.ConnectionError when you have no internet connection. 

@Djones4822 is this how you want it or should pyteamup be handling Requests exceptions in some way?

**Comment by Djones4822** [comment]
We are handling the http errors that can be returned by Teamup API calls - that is the extent that the package should reach. Exceptions with the client connection via requests should be raised as they're passed - it's up to you how you want to handle that situation, pyteamup makes no assumptions and allows them to be raised as it. I think this is the correct behavior, though I'm open to discussion. 

In this case, pyteamup has no awareness or impact on your connection, when that exception is raised there is no logic that teamup could apply.

**Comment by kenstowe** [comment]
Thanks for the response. Sounds like good behaviour.
